fastlane_version "2.24.0"

default_platform :ios

platform :ios do
   lane :example do
      puts("this is my first 🚀 lane")
   end

   lane :ci do|options|
branch = options[:branch]
# 自动获取当前app版本号，并补充当前编译时间为后缀
build_no = get_version_number + '.' + Time.new.strftime("%m%d%H%M")

puts "Begin to run ci"

# 递增build number
increment_build_number(build_number: build_no)

# 开始打包
gym(
# 是否清空以前的编译信息 true：是
clean:true,
# 指定打包方式，Release 或者 Debug
configuration:"Release",
# 指定打包所使用的输出方式，目前支持app-store, package, ad-hoc, enterprise, development
export_method:"development",
# 指定输出文件夹
output_directory:"./fastlane/build",
)

# 使用fir-cli上传ipa
# 请将SDAutolayoutDemo改成你项目要打包的名称
# 请将-T后的数字更改为在fir申请的APIToken
sh "fir publish ./build/SDAutolayoutDemo.ipa -T 396exxxx4b88b012474fcc7c0e1xxxx"

end


end


